---

- block:
    - name: "reset fs_target_dataset"
      set_fact:
        fs_target_dataset: null

    - block:
        - name: "stat {{ fs.name }} current dataset"
          shell: zfs list -H "{{ fs.mountpoint }}" | awk '{print $1}'
          register: t_fs_current_dataset
          changed_when: no

        - name: "set {{ fs.name }} target dataset from current"
          set_fact:
            fs_target_dataset: "{{ t_fs_current_dataset.stdout }}"
          when:
            - t_fs_current_dataset.rc == 0
            - t_fs_current_dataset.stdout != ""
            - not (fs.strict | default(True))

      when:
        - fs.mountpoint | default(false)
        - fs.mountpoint != ''

    - name: "set {{ fs.name }} target dataset if no current"
      set_fact:
        fs_target_dataset: "{{ fs.parent_dataset }}/{{ fs.name }}"
      when:
        - fs_target_dataset is not defined or not fs_target_dataset

    - debug:
        msg: "{{ fs_target_dataset }}"

    - name: "have {{ fs.name }} dataset"
      zfs:
        name: "{{ fs_target_dataset }}"
        state: present
        extra_zfs_properties: "{{ fs_zfs_dataset_properties | combine(fs.properties | default({})) | combine({ 'mountpoint': fs.mountpoint | default('none') }) }}"

  when: fs.type == 'zfs'


- name: "set {{ fs.mountpoint }} permissions"
  file:
    path: "{{ fs.mountpoint }}"
    owner: "{{ fs.owner }}"
    group: "{{ fs.group }}"
    mode: "{{ fs.mode | default(fs_default_mode) }}"
    #recurse: yes
    #follow: no
  when:
    - fs.mountpoint | default(false)
    - fs.mountpoint != ''
